site_name: PrintiPy

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
#  - how-to-guides.md
  - PrintiPy Reference: reference.md
  - PrintiPy Data Objects: data-objects.md
  - PrintiPy Exceptions: exceptions.md
  - explanation.md
